image: node:latest

# Pipeline
stages:
  - install
  - build
  # - exercise_job
  - test

variables:
   npm_config_cache: "$CI_PROJECT_DIR/.npm"
#    CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
   key:
     files:
        - package.json
   paths:
      - .npm
      # - cache/Cypress
      - node_modules


# Jobs 
install_dependencies:
  stage: install
  script:
    - npm ci --cache .npm --prefer-offline
  artifacts:
    paths:
      - node_modules/

bundle_app:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build/

# exercise_job:
#   stage: exercise_job
#   only:
#     - main
#   script:
#     - echo "New job for exercise"
    

test4component:
# Node docker image with Cypress and Chrome pre-installed
  # image: cypress/browsers:node12.14.1-chrome85-ff81
  stage: test
  script:
    - echo "Run tests for component"
    - npm run test

# build_jobX:
#   stage: build
#   only:
#     - develop
#   script:
#     - echo "build job X on demoBranch works"

# test_jobX:
#   stage: test
#   only:
#     - main
#     - branchX
#   script:
#     - echo "Run test job X"